#!/bin/bash

## Assing Vars
# workspaceFolder=$1
# program=$2

echo -e "\e[1m--------- ----------------------------------- ---------"
echo -e "--------- Clean | Generate | Terminal | Cmake ---------"
echo -e "--------- ----------------------------------- ---------";
echo -e "\e[100m \e[1m"
# echo -e "WorkSpace Directory: \e[0m"
# # echo $1	## Bash/File/Program input
# echo $workspaceFolder	## Bash/File/Program input
# echo -e "\e[100m \e[1m \e[0m"
# echo 

# cd $workspaceFolder

##
### Compile
echo -e "\e[1m\e[100m####### ####### ####### ####### ####### ####### #######" ; 
echo "####### ####### ####### Generate ####### ####### #######" ; 
echo "####### ####### ####### ####### ####### ####### #######" ; 
echo -e "\e[0m"
echo ;


# if [ "$workspaceFolderString" == "" ]
# then
# 	echo "Esta vacio el parametro!"
# 	echo $workspaceFolder;
# 	exit; 
# 	exec bash;
# else
# 	echo "NO Esta vacio el parametro!"
# 	# echo $workspaceFolderString;
# 	echo $workspaceFolder;
# fi

## If the build folder does not exist, mkdir
if [ -f "CMakeLists.txt" ]
then
	echo "Existe el archivo CMAKE!"
else
	echo "NO existe el archivo Cmake!"
	exit; 
	exec bash;
fi

## If the build folder does not exist, mkdir
if [ ! -d "build" ]
then
		mkdir -p -v "build"
else
		rm -rf ./build ;
		echo "build folder cleared!"
		mkdir -p -v "build"
fi

echo
echo
##
### Compile
echo -e "\e[1m\e[100m####### ####### ####### ####### ####### ####### #######" ; 
echo "####### ####### ####### Generate ####### ####### #######" ; 
echo "####### ####### ####### ####### ####### ####### #######" ; 
echo -e "\e[0m"
echo ;

echo
cd build;
pwd
echo
echo

# ls -al ;

### Unix 
# cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" ..
# echo
# echo "+++++ Generated using Unix Makefiles +++++"


### Ninja 
time cmake -G "Ninja" -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" -DCMAKE_C_FLAGS="-fdiagnostics-color=always" ..

echo
echo "+++++ Generated using Ninja +++++"

##
###
echo ; 
echo ; 
echo -e "\e[1m***** ***** ******** ****** ***** ***** *****" ; 
echo "***** ***** ***** Generated ***** ***** *****" ; 
echo "***** ***** ***** ********* ***** ***** *****" ; 
echo -e "\e[0m"

# read  -n 1; #
exit; 
exec bash;

